### ISSUE TITLE
Include user site packages for libraries

### ISSUE THREAD

**Issue by Observer46** [kottajl/blender-plug-in-for-modifying-3D-animations#2]
So generally, Blender add-on policy is a bit against installing packages by add-on. But I don't there is a way to comply with that policy, while we need to install custom libraries for certain models, so let's not worry about that.

But there are occasions, where Blender system packages directory is not writable (e.g. I had such situation when installed Blender from Flatpak - Blender runs in a container). In such case, the packages are installed in the user's site packages folder, which by default is inaccessible in Python interpreter in Blender. I suggest adding this directory, as otherwise the add-on will fail on imports of model libraries.

https://github.com/kottajl/blender-plug-in-for-modifying-3D-animations/blob/a9fe36a48e1a078be5fdc0be4ee57aa9f3a5bc14/src/main_addon_file.py#L22-L23

```suggestion
import site

user_site_packages = site.getusersitepackages()

if os.path.exists(user_site_packages) and user_site_packages not in sys.path:
    sys.path.append(user_site_packages) 
```

**Comment by mpedrak** [comment]
Change implemented and tested. Thank you for the contribution.
